--- #YAML:1.0
name:               mysubs
version:            0.20
abstract:           lexical subroutines
author:
    - chocolateboy <chocolate.boy@email.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Hooks::EndOfScope:  0.05
    Devel::Pragma:        0.31
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
