--- #YAML:1.0
name:                mysubs
version:             0.12
abstract:            lexical subroutines
license:             perl
author:              
    - chocolateboy <chocolate.boy@email.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Devel::Pragma:                 0.11
    Scope::Guard:                  0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
